name: Backend-CICD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Generate Prisma client
        working-directory: ./backend
        run: npx prisma generate

      - name: Build Node.js server
        working-directory: ./backend
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST_NAME }}
          username: ${{ secrets.EC2_USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./backend/dist/
          target: "/var/www/bronco_corral_v2/"
