name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  frontend-build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    - name: Deploy frontend to server
      uses: appleboy/ssh-action@master
      with:
        host: 3.21.166.158
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/bronco_corral_v2
          git pull
          cd frontend
          sudo npm install --omit=dev
          pm2 restart bronco_corral_v2
