
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-and-backend-build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend and Backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Build backend
      working-directory: ./backend
      run: npm run build

    - name: Copy frontend build to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: 3.21.166.158
        username: ubuntu
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./frontend/build"
        target: "/var/www/bronco_corral_v2/"

    - name: Copy backend build to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: 3.21.166.158
        username: ubuntu
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./backend/dist"
        target: "/var/www/bronco_corral_v2/"

    - name: SSH into server and restart PM2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 3.21.166.158
        username: ubuntu
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/bronco_corral_v2/
          sudo pm2 restart all
