name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    - name: Copy build to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ec2-3-21-166-158.us-east-2.compute.amazonaws.com
        username: ec2-user
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./frontend/build"
        target: "/var/www/bronco_corral_v2/frontend/build/"
