name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_ENV: production

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 19
      uses: actions/setup-node@v2
      with:
        node-version: '19.x'

    - name: Install dependencies
      run: |
        cd frontend
        npm install
        cd ../backend
        npm install

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Start backend
      run: |
        cd backend
        npm start
