# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: cd frontend && npm ci --prefer-offline --no-audit --progress=false --no-save --no-optional --no-fund
      - name: Build
        run: cd frontend && npm run build
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: cd backend && npm ci --prefer-offline --no-audit --progress=false --no-save --no-optional --no-fund
      - name: Build
        run: cd backend && npm run build
